<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

Below two numpy arrays are given with following columns. 

* Employee Details (1) Employee ID (2) Department (3) Salary
* Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed

Using these two arrays you need to complete set of tasks which are given in the notebook cells (along with hints)

In [1]:
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])

### Task 1: Merge above two numpy arrays using np.hstack

In [8]:
# write code here
np.hstack((employee_details, performance_metrics))

array([['101', 'Sales', '55000', 'Satya Nadella', '101', '85', '5'],
       ['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['103', 'IT', '72000', 'Fatima Razaak', '103', '92', '7'],
       ['104', 'Sales', '60000', 'John Smith', '104', '88', '6'],
       ['105', 'IT', '68000', 'Priya Singh', '105', '79', '4'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['107', 'IT', '71000', 'Michael Brown', '107', '91', '8'],
       ['108', 'Sales', '59000', 'Sunita Sharma', '108', '77', '4'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U21')

### Task 2: Print All the Salaries

In [12]:
# write code here
print(employee_details[:,2])

['55000' '52000' '72000' '60000' '68000' '54000' '71000' '59000' '53000']


### Task 3:  Print All the Salaries in Ascending Order

In [17]:
# write code here
sorted_salaries = employee_details[:,2].sort()
print(employee_details[:,2])

['52000' '53000' '54000' '55000' '59000' '60000' '68000' '71000' '72000']


### Task 4:  Iterate through entire array and print only employee id and name

In [19]:
# write code here
for employee in employee_details:
    print(f"Employee Name -> {employee[-1]} and Employee Id -> {employee[0]}")

Employee Name -> Satya Nadella and Employee Id -> 101
Employee Name -> Emily Johnson and Employee Id -> 102
Employee Name -> Fatima Razaak and Employee Id -> 103
Employee Name -> John Smith and Employee Id -> 104
Employee Name -> Priya Singh and Employee Id -> 105
Employee Name -> Li Wei and Employee Id -> 106
Employee Name -> Michael Brown and Employee Id -> 107
Employee Name -> Sunita Sharma and Employee Id -> 108
Employee Name -> Chen Wei and Employee Id -> 109


### Task 5: Print performance score of all the employees

In [20]:
# write code here
performance_metrics[:,1]

array([85, 78, 92, 88, 79, 81, 91, 77, 83])

### Task 6: Convert these scores to float type by using astype(float) function

In [31]:
# write code here
scores = performance_metrics[:,1].astype(float)
print(scores)

[85. 78. 92. 88. 79. 81. 91. 77. 83.]


### Task 7:  Now print the average performance score of all the employees

In [40]:
# write code here
scores
print(np.average(scores))

83.77777777777777


### Task 8:  Print all the unique departments. You can use np.unique function for this

In [37]:
# first print departments from all the records
records_list = employee_details[:,1]
records_list

# write code here

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

In [41]:
# now print unique departments
unique_records_list = np.unique(records_list)
unique_records_list
# write code here

array(['HR', 'IT', 'Sales'], dtype='<U21')

### Task 9: Print average salary in HR department

In [5]:
# First print all the records in HR department
dept_name = 'HR'
list_of_hr_records = employee_details[employee_details[:, 1] == dept_name]
list_of_hr_records
# write code here


array([['102', 'HR', '52000', 'Emily Johnson'],
       ['106', 'HR', '54000', 'Li Wei'],
       ['109', 'HR', '53000', 'Chen Wei']], dtype='<U21')

In [9]:
# Now from these records only print  the salary column. Convert that to float using astype(float) function
salary_col = list_of_hr_records[:,2].astype(float)
salary_col

# write code here

array([52000., 54000., 53000.])

In [10]:
# Take an average of this column using np.mean() function
avg_salary = np.mean(salary_col)
avg_salary
# write code here

np.float64(53000.0)