In [2]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
python_list = [1, 2, 3]

In [4]:
python_list

[1, 2, 3]

In [5]:
python_list = list(range(100))

In [6]:
python_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [9]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [10]:
sys.getsizeof(numpy_array)

912

In [11]:
numpy_array.nbytes

800

In [12]:
import time

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x,y in zip(l1, l2)]
end_time = time.time()

print(end_time - start_time)

0.11177420616149902


In [15]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)

start_time = time.time()
n3 = n1 + n2
end_time = time.time()

print(end_time - start_time)

0.010705947875976562


In [5]:
rev_q1 = np.array([[10, 12, 9], [15, 11, 1]])
print(rev_q1.ndim)

2


In [6]:
rev_q1

array([[10, 12,  9],
       [15, 11,  1]])

In [7]:
rev_q1[1]

array([15, 11,  1])

In [8]:
rev_q1[1][1]

np.int64(11)

In [9]:
rev_q1[1, 1]

np.int64(11)

In [10]:
rev_q1[1][1] = 24

In [11]:
rev_q1

array([[10, 12,  9],
       [15, 24,  1]])

In [12]:
rev = np.array([[10, 12, 9], [15, 11, 1]], dtype=np.float64)
print(rev_q1.ndim)

2


In [13]:
rev.dtype

dtype('float64')

In [14]:
rev.size

6

In [15]:
rev.itemsize

8

In [16]:
rev.shape

(2, 3)

In [17]:
rev.sort

<function ndarray.sort(axis=-1, kind=None, order=None, *, stable=None, descending=None)>

In [18]:
rev.sort()

In [19]:
rev

array([[ 9., 10., 12.],
       [ 1., 11., 15.]])

In [20]:
np.sort(rev, axis=None)

array([ 1.,  9., 10., 11., 12., 15.])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [24]:
np.arange(10, 100, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [26]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [27]:
rev

array([[ 9., 10., 12.],
       [ 1., 11., 15.]])

In [28]:
rev.flatten()

array([ 9., 10., 12.,  1., 11., 15.])

In [29]:
print(rev)

[[ 9. 10. 12.]
 [ 1. 11. 15.]]


In [30]:
rev.reshape(3, 2)

array([[ 9., 10.],
       [12.,  1.],
       [11., 15.]])

In [31]:
rev.reshape(5, 4)

ValueError: cannot reshape array of size 6 into shape (5,4)

In [32]:
rev.reshape(6, 1)

array([[ 9.],
       [10.],
       [12.],
       [ 1.],
       [11.],
       [15.]])

In [33]:
rev.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [34]:
rev.reshape(3, 2)

array([[ 9., 10.],
       [12.,  1.],
       [11., 15.]])

In [35]:
rev.min()

np.float64(1.0)

In [36]:
rev.max()

np.float64(15.0)

In [37]:
rev.sum()

np.float64(58.0)

In [38]:
rev.sum(axis=1)

array([31., 27.])

In [39]:
rev.sum(axis=0)

array([10., 21., 27.])

In [40]:
for row in rev:

SyntaxError: incomplete input (4128252998.py, line 1)

In [41]:
for row in rev:
    print(f"row -> {row}")

row -> [ 9. 10. 12.]
row -> [ 1. 11. 15.]


In [42]:
rev

array([[ 9., 10., 12.],
       [ 1., 11., 15.]])

In [43]:
a = np.array([1, 4, 81])

In [44]:
np.sqrt(a)

array([1., 2., 9.])

In [45]:
np.std(a)

np.float64(37.025516726831626)

In [46]:
np.square(a)

array([   1,   16, 6561])

In [47]:
q1 = np.array([
    [200, 220, 250], #Product A
    [150, 180, 210], #Product B

SyntaxError: incomplete input (1430847217.py, line 3)

In [48]:
q1 = np.array([
    [200, 220, 250], #Product A
    [150, 180, 210], #Product B
    [300, 330, 360] #Proudct C
])

q2 = np.array([
    [209, 231, 259],
    [155, 192, 222],
    [310,340, 375]
])



In [49]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [50]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [51]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [52]:
prices = np.array([
    [10, 12, 11] #Prices for Product A in different regions
    [8, 9, 10] #Prices for Product B

SyntaxError: incomplete input (42139602.py, line 3)

In [55]:
prices = np.array([
    [10, 12, 11], #Prices for Product A in different regions
    [8, 9, 10], #Prices for Product B
    [15, 16, 17] #Prices for Product C
])

In [56]:
q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [62]:
q1_discount = q1_revenue*0.3 # Giving 30% discount means
q1_discount

array([[ 600.,  792.,  825.],
       [ 360.,  486.,  630.],
       [1350., 1584., 1836.]])

In [60]:
net_revenue = q1_revenue - q1_discount

In [61]:
print(net_revenue)

[[1400. 1848. 1925.]
 [ 840. 1134. 1470.]
 [3150. 3696. 4284.]]


In [63]:
np.sum(net_revenue)

np.float64(19747.0)

In [64]:
features = np.array([
    [2000, 3], # house 1
    [1800, 2] #house 2
])
features

array([[2000,    3],
       [1800,    2]])

In [67]:
weights = np.array([150, 50000])

np.dot(features, weights)

array([450000, 370000])

In [68]:
np.hstack, np.vstack, np.hsplit(transaction, [3]), np.vsplit, < (in all list), sales.max(), np.argmax(monthly_salws), astype, transactions[transactions[:,0]=='102
    ]

SyntaxError: unterminated string literal (detected at line 1) (3244554085.py, line 1)